### ISSUE TITLE
Structure of the installation directory

### ISSUE THREAD

**Issue by thelfer** [PaulSt/NGSTrefftz#5]
This issue is created as part of the review of the JOSS paper (https://github.com/openjournals/joss-reviews/issues/4135).

The installation directory of `NGSTrefftz` is currently as follows:

~~~~
$ tree -d .
.
├── ngstents
└── ngstrefftz
~~~~

This structure is not standard and worse, not compatible with the one of `NGSolve` which installs its `python` module in `lib/python3/dist-packages/`.

**Comment by PaulSt** [comment]
Hmm, are you passing `DCMAKE_INSTALL_PREFIX` to cmake?

I believe, you will get the behavior you are looking for when you do *not* tell cmake a install prefix. Then, the install directory of ngsolve is used, which should then be `lib/python3/dist-packages/`

This directory should also be in the `PYTHONPATH` (for ngsolve to work) so that the tests should work out of the box https://github.com/PaulSt/NGSTrefftz/issues/6

If I am understanding correctly, and this indeed solves the issue, then I could put some kind of warning into the cmake in the case of `DCMAKE_INSTALL_PREFIX` to inform the user that the path deviates from the ngsolve install path and that this needs to be added to the pythonpath.

**Comment by thelfer** [comment]
Concerning the tests, you seem to suggest that one have to install `NGSTrefftz` **before** running the tests. This is also non standard. The standard way is:

```bash
$ cmake
$ make
$ make test
$ make install 
```

**Comment by PaulSt** [comment]
Thank you for clearing that up, this was very helpful! I updated the cmake file with ad9e06a33e4319a9f76250d7c008fd25c5beb8b3 to hopefully meet all specifications!
